config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :bookings
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    validates :full_name, :email, :room, :date, :user_id, presence: true
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.order(created_at: :asc)
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    #@booking = Booking.new
    @booking = current_user.bookings.build
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    #@booking = Booking.new(booking_params)
    @booking = current_user.bookings.build(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: "Reserva criada." }
        format.json { render :show, status: :created, location: @booking }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: "Reserva atualizada." }
        format.json { render :show, status: :ok, location: @booking }
        format.js
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Reserva cancelada." }
      format.json { head :no_content }
      format.js
    end
  end

  def correct_user
    @booking = current_user.bookings.find_by(id: params[:id])
    redirect_to bookings_path, notice: "Não autorizado!" if @booking.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:full_name, :email, :room, :date, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bookings/_booking_row.html.erb
<tr id="bookingRow_<%= booking.id %>">
  <td><%= booking.full_name %></td>
  <td><%= booking.email %></td>
  <td><%= booking.room %></td>
  <td><%= booking.date %></td>
  <td><%= link_to 'Ver reserva', booking, class:"btn btn-primary", data: { bs_toggle: "modal", bs_target: "#showBookingModal", remote: true } %></td>
  <td><%= link_to 'Editar reserva', edit_booking_path(booking), class:"btn btn-secondary", data: { bs_toggle: 'modal', bs_target: '#editBookingModal', remote: true } %></td>
  <td><%= link_to 'Cancelar reserva', booking, method: :delete, data: { confirm: 'Tem certeza que deseja cancelar a reserva?', remote: true }, class:"btn btn-danger" %></td>
</tr>

app/views/bookings/_error.html.erb
<% if booking.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
    <ul>
      <% booking.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: false) do |form| %>
  <div class="modal-body">
  <div id="errors"></div>
   
    <div class="field form-group mt-3">
      <%= form.label :full_name %>
      <%= form.text_field :full_name, class:"form-control", :required => 'Campo vazio! Preencha corretamente' %>
    </div>
    <div class="field form-group mt-3">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control", :required => 'Campo vazio! Preencha corretamente'  %>
    </div>
    <div class="field form-group mt-3">
      <%= form.label :room %>
      <%= form.text_field :room, class:"form-control", :required => 'Campo vazio! Preencha corretamente'  %>
    </div>
    <div class="field form-group mt-3">
      <%= form.number_field :user_id, id: :booking_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
    <br>
    <div class="field form-group mt-3">
      <%= form.label :date %>
      <%= form.datetime_select :date %>
    </div>
    <br>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Fechar</button>
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/bookings/_show.html.erb
<div class="modal-body">
  <div class="jumbotron">
    <h1 class="display-4"><%= booking.full_name %></h1>
    <p class="lead"><%= booking.email %></p>
    <hr class="my-4">
    <p><%= booking.room %></p>
    <p class="lead"><%= booking.date %></p>
  </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-secondary close-modal" data-bs-dismiss="modal">Fechar</button>
</div>

app/views/bookings/create.js.erb
<% if @booking.errors.any? %>
    $("#errors").html("<%= escape_javascript render('error', booking: @booking)%>");
<% else %>
    $("#bookingTable").append("<%= escape_javascript render('booking_row', booking: @booking)%>");
    $(".close-modal").click();
<% end %>

app/views/bookings/destroy.js.erb
$("#bookingRow_<%= @booking.id %>").remove();

app/views/bookings/edit.html.erb
<h1>Editar reserva</h1>

<%= render 'form', booking: @booking %>

<br>

<%= link_to 'Ver reserva', @booking, class:"btn btn-primary" %>
<%= link_to 'Voltar', bookings_path, class:"btn btn-dark" %>

app/views/bookings/edit.js.erb
$("#editBookingForm").html("<%= escape_javascript render('form', booking: @booking)%>");

app/views/bookings/index.html.erb
<h1>Reservar sala</h1>

<table class="table table-dark table-hover table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Sala</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="bookingTable">
    <% @bookings.each do |booking| %>
      <%= render 'booking_row', booking: booking %>
    <% end %>
  </tbody>
</table>


<br>

<% if user_signed_in? %>
  <%= link_to 'Nova reserva', new_booking_path, class:"btn btn-success", data: { bs_toggle: 'modal', bs_target: '#newBookingModal', remote: true } %>
<% end %>



<div class="modal fade" id="newBookingModal" tabindex="-1" aria-labelledby="newBookingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newBookingModalLabel">Reservar sala</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="newBookingForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="editBookingModal" tabindex="-1" aria-labelledby="editBookingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editBookingModalLabel">Editar reserva</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="editBookingForm">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="showBookingModal" tabindex="-1" aria-labelledby="showBookingModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showBookingModalLabel">Ver reserva</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="showBookingDetails">
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Nova reserva</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Voltar', bookings_path, class:"btn btn-dark"%>

app/views/bookings/new.js.erb
$("#newBookingForm").html("<%= escape_javascript render('form', booking: @booking)%>");

app/views/bookings/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @booking.full_name %></h1>
  <p class="lead"><%= @booking.email %></p>
  <hr class="my-4">
  <p><%= @booking.room %></p>
  <p class="lead"><%= @booking.date %></p>
</div>



<%= link_to 'Editar reserva', edit_booking_path(@booking), class:"btn btn-secondary" %>
<%= link_to 'Voltar', bookings_path, class:"btn btn-dark" %>

app/views/bookings/show.js.erb
$("#showBookingDetails").html("<%= escape_javascript render('show', booking: @booking) %>");

app/views/bookings/update.js.erb
<% if @booking.errors.any? && !current_user %>
  alert('Preenchimento incorreto!');
<% else %>
  $("#bookingRow_<%= @booking.id %>").replaceWith("<%= escape_javascript render('booking_row', booking: @booking)%>");
  $(".close-modal").click();
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Projeto ESL Sistemas", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
            <%= link_to "Reservas", bookings_path, class:"nav-link" %>
        </li>

        <%if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Editar perfil", edit_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Cadastrar", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Projeto ESL Sistemas</h1>

<h2>Reserva de salas</h2>

<p>Projeto para o processo seletivo</p>

<%= link_to "Ver reservas", bookings_path, class:"btn btn-dark" %>
<%= link_to "Acessar conta", new_user_session_path, class:"btn btn-primary" %>
<%= link_to "Criar conta", new_user_registration_path, class:"btn btn-success" %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Projeto ESL Sistemas</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
    
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <br>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>